In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [2]:
df=pd.read_csv(r"C:\Juneinter\midterm_substitution.csv")
df

   Country Code  Series Code  growth(Y)  inflation    debt
0           KOR         1990   8.734757  10.108090  12.940
1           KOR         1991   9.267071   9.484639  12.078
2           KOR         1992   5.077884   7.743556  11.814
3           KOR         1993   5.766866   6.196906  11.041
4           KOR         1994   8.112865   8.102666   9.804
5           KOR         1995   8.473632   6.939947   8.657
6           KOR         1996   6.574239   4.255252   7.978
7           KOR         1997   4.933581   4.065016   9.916
8           KOR         1998  -6.151130   4.616319  14.197
9           KOR         1999  10.520250  -1.184720  16.210
10          KOR         2000   8.017418   0.892545  16.682
11          KOR         2001   3.726414   3.478972  17.229
12          KOR         2002   6.813311   3.033714  17.041
13          KOR         2003   2.401073   3.448993  19.803
14          KOR         2004   4.484912   3.127829  22.422
15          KOR         2005   3.703595   1.042276  25.899
16          KOR         2006   4.625217  -0.223200  28.121
17          KOR         2007   4.931903   2.418321  27.431
18          KOR         2008   2.051381   2.826380  26.949
19          KOR         2009   0.190517   3.608662  29.984
20          KOR         2010   5.967519   2.738284  29.490
21          KOR         2011   2.887463   1.281415  30.235
22          KOR         2012   1.756044   1.251358  30.800
23          KOR         2013   2.428867   1.019217  33.707
24          KOR         2014   2.694343   0.906895  35.479
25          KOR         2015   2.249662   3.185331  37.287
26          KOR         2016   2.465813   1.986000  37.621
27          KOR         2017   2.621222   2.222854  37.678
28          KOR         2018   2.731492   1.523820  35.932

In [3]:
infla_x_data=df.iloc[:,[3]].values
debt_x_data=df.iloc[:,[4]].values
growth_y_data=df.iloc[:,[2]].values

In [4]:
W=tf.Variable(tf.random.normal([1], mean=0.0), name="weight")
b=tf.Variable(tf.random.normal([1], mean=0.0), name="bias")

def hypothesis(X):
    return W*X+b

def cost_fn(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred-y_true))

optimizer=tf.optimizers.SGD(learning_rate=0.001)

In [8]:
for step in range(10001):  #인플레이션과 경제성장률 상관분석
    with tf.GradientTape() as g:
        pred=hypothesis(infla_x_data)
        cost=cost_fn(pred, growth_y_data)
        
        gradients=g.gradient(cost, [W,b])
        
    optimizer.apply_gradients(zip(gradients, [W,b]))
    
    if step % 2500==0:
        print("cost: ", cost.numpy())
        print("slope: ", W.numpy())
        print("y-intercept: ", b.numpy())

cost:  9.800826
slope:  [0.33581242]
y-intercept:  [3.2566388]
cost:  9.800826
slope:  [0.33581242]
y-intercept:  [3.2566388]
cost:  9.800826
slope:  [0.33581242]
y-intercept:  [3.2566388]
cost:  9.800826
slope:  [0.33581242]
y-intercept:  [3.2566388]
cost:  9.800826
slope:  [0.33581242]
y-intercept:  [3.2566388]

In [ ]:
infla_x_data

In [ ]:
growth_y_data